/* eslint-disable */
export default Menus = {
  menus: [
    {
      id: "Vinte e seis mil quinhentos setenta e seis",
      "menu-items": [
        {
          id: "Noventa e quatro mil duzentos e noventa e oito",
          name: "3 Asas De Frango",
          position: 1,
          description: "Concurso, Picante e Suculento. Original ou Peri-Crusted",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e setenta e um",
              name: "3 Asas De Frango",
              position: 1,
              price: "250.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Appeteasers",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e um",
          name: "Os Fígados de frango e português Rolo",
          position: 2,
          description:
            "Os Fígados de frango Coberto com PERi-PERi Molho, Servido com Um Rolo Para Absorver O Molho",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e setenta e quatro",
              name: "Os Fígados de frango e português Rolo",
              position: 1,
              price: "250.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Appeteasers",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e quatro",
          name: "Picante Azeitonas Mistas (V)",
          position: 3,
          description: "Co-Estrelando com Alho, Pimenta e Pimentão",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e setenta e sete",
              name: "Picante Azeitonas Mistas (V)",
              position: 1,
              price: "215.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Appeteasers",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e sete",
          name: "Hummus com PERI-PERI Garoa (V)",
          position: 4,
          description:
            "Despeje Smoky PERi-PERi Óleo Cremoso Hummus e Cavar com Tiras De Quente Pita",
          images: [],
          "sub-items": [
            {
              id: "Duzentos e vinte quatro mil, quatrocentos e oitenta",
              name: "Hummus com PERI-PERI Garoa (V)",
              position: 1,
              price: "215.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Appeteasers",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e dez",
          name: "Pimenta Vermelha Dip (V)",
          position: 5,
          description:
            "Mergulho Em Temping Assado, Pimenta Vermelha e Pimenta Tempero do Mergulho Quente Pita Tiras",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e oitenta e três",
              name: "Pimenta Vermelha Dip (V)",
              position: 1,
              price: "205.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Appeteasers",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e treze",
          name: "Appeteaser Prato",
          position: 6,
          description: "Escolher quaisquer Três Appeteasers",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e oitenta e seis",
              name: "Appeteaser Prato",
              position: 1,
              price: "615.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Appeteasers",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e dezesseis",
          name: "Todos Juntos Agora (V)",
          position: 7,
          description:
            "Picante Misturado Azeitonas, Pimentão Vermelho Mergulho, Hummus com PERi-PERi Garoa e Quente Pita Tiras",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e oitenta e nove",
              name: "Todos Juntos Agora (V)",
              position: 1,
              price: "520.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Appeteasers",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil quinhentos oitenta e dois",
      name: "Fino lados",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e trinta e quatro",
          name: "PERi-PERi Cunhas (P)",
          position: 8,
          description: "",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos e vinte dois",
              name: "Regular",
              position: 1,
              price: "190.00",
              consumable: "1:1",
              cuisine_name: "Comida Rápida",
              category_name: "Fino lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos e vinte cinco",
              name: "Grande",
              position: 2,
              price: "330.00",
              consumable: "1:1",
              cuisine_name: "Comida Rápida",
              category_name: "Fino lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e trinta e sete",
          name: "Milho Em Espiga",
          position: 9,
          description: "",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil e quinhentos e vinte oito",
              name: "Regular",
              position: 1,
              price: "190.00",
              consumable: "1:1",
              cuisine_name: "Comida Rápida",
              category_name: "Fino lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos trinta e um",
              name: "Grande",
              position: 2,
              price: "330.00",
              consumable: "1:1",
              cuisine_name: "Comida Rápida",
              category_name: "Fino lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil quinhentos oitenta e oito",
      name: "Peri-peri frango",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e quarenta e nove",
          name: "1/4 de Frango",
          position: 10,
          description: "Trimestre de Frango Marinado com PERi-PERi Molho e Grelhado",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos quarenta e três",
              name: "Em sua própria",
              position: 1,
              price: "385.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos quarenta e seis",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "485.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos quarenta e nove",
              name: "Com 2 Lados",
              position: 3,
              price: "575.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e cinqüenta e dois",
          name: "1/2 Frango",
          position: 11,
          description: "Metade de Frango Marinado com PERi-PERi Molho e Grelhado",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos cinqüenta e dois",
              name: "Em sua própria",
              position: 1,
              price: "Quarto individual 685.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos cinqüenta e cinco",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "785.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos cinquenta e oito",
              name: "Com 2 Lados",
              position: 3,
              price: "875.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e cinquenta e cinco",
          name: "5 Asas De Frango",
          position: 12,
          description: "Sabores originais ou PERi-PEREi Crosta (P)",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos sessenta e um",
              name: "Em sua própria",
              position: 1,
              price: "475.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos sessenta e quatro",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "575.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos sessenta e sete",
              name: "Com 2 Lados",
              position: 3,
              price: "665.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e cinquenta e oito",
          name: "Asa De Roleta",
          position: 13,
          description: "10 Asas em PERi-PERi Sabores",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos e setenta",
              name: "Asa De Roleta",
              position: 1,
              price: "750.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e sessenta e um",
          name: "Frango Inteiro",
          position: 14,
          description: "Todo o Frango Marinado em PERi-PERi Molho e Grelhado",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos setenta e três",
              name: "Frango Inteiro",
              position: 1,
              price: "1350.00",
              consumable: "1:4",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e sessenta e quatro",
          name: "Frango Borboleta",
          position: 15,
          description: "Suculenta Dupla de Peito de Frango em Pele Crocante",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos setenta e seis",
              name: "Em sua própria",
              position: 1,
              price: "495.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos setenta e nove",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "595.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos oitenta e dois",
              name: "Com 2 Lados",
              position: 3,
              price: "Quarto individual 685.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e sessenta e sete",
          name: "A Espetada",
          position: 16,
          description: "Marinado Coxas de Frango e Frescas Pimentas, Servido no Espeto",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos oitenta e cinco",
              name: "Em sua própria",
              position: 1,
              price: "695.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos oitenta e oito",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "795.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos noventa e um",
              name: "Com 2 Lados",
              position: 3,
              price: "885.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e setenta",
          name: "Espetada De Carnaval",
          position: 17,
          description:
            "Chama-Grelhado PERi-PERi Coxas, Recheado com queijo Feta e a Salsa, Espetada com uma mistura de Pimentas",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos e noventa quatro",
              name: "Em sua própria",
              position: 1,
              price: "Quarto individual 825.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos e noventa e sete",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "925.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos",
              name: "Com 2 Lados",
              position: 3,
              price: "1015.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e setenta e três",
          name: "Frango Grelhado Propostas",
          position: 18,
          description: "Suculenta e Tenra, Deliciosa com Todos os Lados",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e três",
              name: "Em sua própria",
              position: 1,
              price: "200.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e seis",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "300.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e nove",
              name: "Com 2 Lados",
              position: 3,
              price: "390.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Peri-peri frango",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil quinhentos e noventa quatro",
      name: "A partilha de pratos",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e setenta e nove",
          name: "Prato Cheio",
          position: 19,
          description: "Para 3 a 4 Pessoas, Todo o Frango com 2 Grandes ou 4 Regular Experiências",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e quinze",
              name: "Com 2 Grandes Lados",
              position: 1,
              price: "1765.00",
              consumable: "1:4",
              cuisine_name: "Comida Rápida",
              category_name: "A partilha de pratos",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e dezoito",
              name: "Com 4 Regular Os Lados",
              position: 2,
              price: "1765.00",
              consumable: "1:4",
              cuisine_name: "Comida Rápida",
              category_name: "A partilha de pratos",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e oitenta e dois",
          name: "Sem Ossos Prato",
          position: 20,
          description:
            "Para 2-3 Pessoas, Frango Borboleta e uma Espetada, com 2 Grandes ou 4 Regular os Lados",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e vinte e um",
              name: "Com 2 Grandes Lados",
              position: 1,
              price: "1550.00",
              consumable: "1:3",
              cuisine_name: "Indiana",
              category_name: "A partilha de pratos",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e vinte e quatro",
              name: "Com 4 Regular Os Lados",
              position: 2,
              price: "1550.00",
              consumable: "1:3",
              cuisine_name: "Indiana",
              category_name: "A partilha de pratos",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e oitenta e cinco",
          name: "Jumbo Prato",
          position: 21,
          description: "Para 4 a 6 Pessoas, 2 Frangos Inteiros e 5 Grandes Lados",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e vinte e sete",
              name: "Jumbo Prato",
              position: 1,
              price: "3595.00",
              consumable: "1:6",
              cuisine_name: "Comida Rápida",
              category_name: "A partilha de pratos",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil seiscentos",
      name: "Sobremesa",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e noventa e nove",
          name: "Sobremesa",
          position: 22,
          description: "",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e sessenta e cinco",
              name: "Caramelo Bolo De Queijo",
              position: 1,
              price: "230.00",
              consumable: "1:1",
              cuisine_name: "Sobremesas",
              category_name: "Sobremesa",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e sessenta e oito",
              name: "Iluminar Bolo De Chocolate",
              position: 2,
              price: "230.00",
              consumable: "1:1",
              cuisine_name: "Sobremesas",
              category_name: "Sobremesa",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil quinhentos setenta e nove",
      name: "Os lados",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e dezenove",
          name: "PERi-PERi Chips (P)",
          position: 23,
          description: "Crocante de batata frita com PERi-PERi Molho",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e noventa e dois",
              name: "Regular",
              position: 1,
              price: "130.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e noventa e cinco",
              name: "Grande",
              position: 2,
              price: "220.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil, trezentos e vinte dois",
          name: "Picante Arroz",
          position: 24,
          description: "Arroz frito picante",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quatrocentos e noventa e oito",
              name: "Regular",
              position: 1,
              price: "130.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentos e vinte quatro mil e quinhentas um",
              name: "Grande",
              position: 2,
              price: "220.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil, trezentos e vinte cinco",
          name: "Salada De Repolho (M)",
          position: 25,
          description: "Repolho, Cenoura, Nando&amp;#039;s Especiais de Maionese",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil e quinhentos quatro",
              name: "Regular",
              position: 1,
              price: "130.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil e quinhentos sete",
              name: "Grande",
              position: 2,
              price: "220.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil, trezentos e vinte oito",
          name: "Grelhado, Vegetais",
          position: 26,
          description: "Grelhado, Legumes Variados",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil e quinhentos dez",
              name: "Regular",
              position: 1,
              price: "130.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil quinhentos e treze",
              name: "Grande",
              position: 2,
              price: "220.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e trinta e um",
          name: "Pão De Alho",
          position: 27,
          description: "Torradas De Alho Com Sabor De Pão",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil e quinhentos dezesseis",
              name: "Regular",
              position: 1,
              price: "130.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil e quinhentos dezenove",
              name: "Grande",
              position: 2,
              price: "220.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Os lados",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil quinhentos oitenta e cinco",
      name: "Saladas",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e quarenta",
          name: "Português Salada",
          position: 28,
          description:
            "Tomate fresco, Nando&amp;#039;s Peri-Azeitonas, Misto, Pimentão, Pepino e Cebola em Uma Cama de Alface Crocante",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos trinta e quatro",
              name: "Português Salada",
              position: 1,
              price: "245.00",
              consumable: "1:1",
              cuisine_name: "Salada",
              category_name: "Saladas",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e quarenta e três",
          name: "Mediterrâneo Salada",
          position: 29,
          description:
            "Piccolo Tomate, Pepino, Pimentão e Folhas Mistas. Polvilhado com Azeitonas e Queijo Feta",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos trinta e sete",
              name: "Mediterrâneo Salada",
              position: 1,
              price: "350.00",
              consumable: "1:1",
              cuisine_name: "Salada",
              category_name: "Saladas",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e quarenta e seis",
          name: "Caesar Salad (M)",
          position: 30,
          description:
            "Cos Alface Polvilhado com Queijo Parmesão, César de Vestir e Croutons Crocantes",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil quinhentos e quarenta",
              name: "Caesar Salad (M)",
              position: 1,
              price: "245.00",
              consumable: "1:1",
              cuisine_name: "Salada",
              category_name: "Saladas",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil quinhentos noventa e um",
      name: "Tente de novo someting",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e setenta e seis",
          name: "Cataplana Algarvia",
          position: 31,
          description:
            "PERi-PERi Coxas de Frango, Misto, Pimentão, Grão de bico e Picante, Arroz e Cataplana de Molho",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e doze",
              name: "Cataplana Algarvia",
              position: 1,
              price: "795.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Tente de novo someting",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
    {
      id: "Vinte e seis mil quinhentos e noventa e sete",
      name: "Hambúrgueres, pitas, wraps",
      position: "0",
      "menu-items": [
        {
          id: "Noventa e quatro mil trezentos e oitenta e oito",
          name: "Chicken Wrap (Y)",
          position: 32,
          description:
            "Levemente Torrados, de quebra, Generosamente Preenchido Com o Concurso de Frango, Pimenta, Geléia de Alface de Folha Verde e Picante Molho de Iogurte",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e trinta",
              name: "Em sua própria",
              position: 1,
              price: "335.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e trinta e três",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "435.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e trinta e seis",
              name: "Com 2 Lados",
              position: 3,
              price: "525.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e noventa e um",
          name: "Peito De Frango Burger (M)",
          position: 33,
          description:
            "Servido em Uma Torrada português Rolo com Frescos, Rúcula, Tomate, Picles de Cebola Vermelha e Perinaise",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e trinta e nove",
              name: "Em sua própria",
              position: 1,
              price: "335.00",
              consumable: "1:1",
              cuisine_name: "Burger",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e quarenta e dois",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "435.00",
              consumable: "1:1",
              cuisine_name: "Burger",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e quarenta e cinco",
              name: "Com 2 Lados",
              position: 3,
              price: "525.00",
              consumable: "1:1",
              cuisine_name: "Burger",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e noventa e quatro",
          name: "Frango César De Moldagem (M)",
          position: 34,
          description:
            "Servido em Uma Torrada Envoltório Completo De PERi-PERi, Frango Crocante, Croutons, Queijo Parmesão e Tomates Secos, Todos Sufocado no Cremosa César de Vestir",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e quarenta e oito",
              name: "Em sua própria",
              position: 1,
              price: "335.00",
              consumable: "1:1",
              cuisine_name: "Comida Rápida",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e cinqüenta e um",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "435.00",
              consumable: "1:1",
              cuisine_name: "Comida Rápida",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e cinquenta e quatro",
              name: "Com 2 Lados",
              position: 3,
              price: "525.00",
              consumable: "1:1",
              cuisine_name: "Comida Rápida",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
        {
          id: "Noventa e quatro mil trezentos e noventa e sete",
          name: "Frango Pita (M)",
          position: 35,
          description:
            "Servido em Um Levemente Torrado Pita, Recheado Com Frango Propostas, Nítidas Vegetariano Salada e Cremoso Chicote",
          images: [],
          "sub-items": [
            {
              id: "Duzentas e vinte e quatro mil seiscentos e cinquenta e sete",
              name: "Em sua própria",
              position: 1,
              price: "335.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e sessenta",
              name: "Com 1 Regular Lado",
              position: 2,
              price: "435.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
            {
              id: "Duzentas e vinte e quatro mil seiscentos e sessenta e três",
              name: "Com 2 Lados",
              position: 3,
              price: "525.00",
              consumable: "1:1",
              cuisine_name: "Indiana",
              category_name: "Hambúrgueres, pitas, wraps",
              discount: { type: "", amount: "0.00" },
              tags: [],
            },
          ],
        },
      ],
    },
  ],
}
